name: Waka Readme

on:
  schedule:
    # Runs at 12am CET/CEST (Holland local time)
    - cron: "0 22 * * *" # 22:00 UTC -> 12:00 AM (Holland local time)
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SHOW_TITLE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          TIME_RANGE: all_time
          CODE_LANG: typescript
