name: Waka Readme

on:
  schedule:
    # Runs at 12am CET/CEST (Holland local time)
    - cron: "0 22 * * *" # 22:00 UTC -> 12:00 AM (Holland local time)
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          DEBUG_LOGGING: false
          SHOW_OS: true
          SHOW_LANGUAGE: true
          SHOW_COMMIT: true
          TIME_RANGE: all_time
